In [1]:
import pandas as pd
import plotly.express as px

In [6]:
df = pd.read_csv("./data/iris.csv")    
plot = px.scatter(df, x="sepal_length", y="petal_length", color="species", title="Iris Dataset Scatter Plot")
plot.show()

In [7]:
df1 = df.groupby("species").mean().reset_index()
bar_plot = px.bar(df1, x="species", y=["sepal_length", "petal_length"], barmode="group", title="Average Sepal and Petal Length by Species")
bar_plot.show()

In [9]:
box_plot = px.box(df, x="species", y="sepal_width", title="Sepal Width Distribution by Species")
box_plot.show()

In [11]:
histogram_plot = px.histogram(df, x="sepal_length", nbins=20, title="Petal Length Distribution")
histogram_plot.show()

In [13]:
city_df = pd.read_csv("./data/us-cities-top-1k.csv")
map_plot = px.scatter_map(city_df, lat="lat", lon="lon", size='Population', hover_name="City", hover_data=["State", "Population"])
map_plot.show()

In [15]:
tips_df = pd.read_csv("./data/tips.csv")
pie_plot = px.pie(tips_df, names='sex', values='tip', hole=0.5, title='Tips Distribution by Gender')
pie_plot.show()

In [16]:
import streamlit as st
st.markdown("# Hello, Streamlit!")

2025-10-16 18:11:34.432 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-16 18:11:34.502
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /Users/peter.gross/Developer/python/plutora/venv/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]
2025-10-16 18:11:34.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-10-16 18:11:34.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Streamlit requires raw Python (.py) files, not .ipynb.
For more information, please see https://docs.streamlit.io

In [2]:
import plutora as p
p_json = p.get_bookings()
result = p.enrich_bookings_with_names(p_json)
df = pd.DataFrame(result.get('resultSet', []))
df.loc[:, ['environmentName', 'startDate', 'endDate', 'releaseName', 'status', 'state']]

Fetching release and environment names for 2 bookings...
Processed 2/2 bookings
Completed processing all 2 bookings
Found 2 unique releases
Found 1 unique environments

,environmentName,startDate,endDate,releaseName,status,state
0,Mobility_SIT,2025-05-27T00:00:00,2025-07-29T00:00:00,Risk Calculation App Project,Pending,Conflicting
1,Mobility_SIT,2025-04-03T00:00:00,2025-06-05T00:00:00,Mobile App IT Ops Project,Pending,Available

In [3]:
df.loc[df.state == "Conflicting", ['startDate', 'endDate', 'releaseName', 'environmentName', 'status', 'state']]

,startDate,endDate,releaseName,environmentName,status,state
0,2025-05-27T00:00:00,2025-07-29T00:00:00,Risk Calculation App Project,Mobility_SIT,Pending,Conflicting

In [4]:
p_json = p.get_bookings()
result_set = pd.DataFrame(p_json.get('resultSet', []))
result_set

,id,environmentId,isEnvironmentGroup,releaseId,phaseId,tebrId,startDate,endDate,status,state,statusUpdaterId,timeStamp
0,9321451d-132f-f011-abc0-06b344cd22ba,dff20bbc-082f-f011-abc0-06b344cd22ba,False,7321451d-132f-f011-abc0-06b344cd22ba,9021451d-132f-f011-abc0-06b344cd22ba,None,2025-05-27T00:00:00,2025-07-29T00:00:00,Pending,Conflicting,None,None
1,ee07dbe0-112f-f011-abc0-06b344cd22ba,dff20bbc-082f-f011-abc0-06b344cd22ba,False,cc07dbe0-112f-f011-abc0-06b344cd22ba,ea07dbe0-112f-f011-abc0-06b344cd22ba,None,2025-04-03T00:00:00,2025-06-05T00:00:00,Pending,Available,None,None

In [5]:

token = p.getAccessToken()
p_envs = p.Get_Envs_List(token)
envs_list = pd.DataFrame(p_envs)
envs_list

,id,name,url,linkedSystem,environmentGroupIDs,buildNumber,usageWorkItem,status,color,lastModifiedDate,lastModifiedBy
0,8f613e4f-2ce5-ee11-abc0-06b344cd22ba,3DCS_SIT,,3DCS,[{'id': '19e0f674-9c3c-f011-abc0-06b344cd22ba'...,None,SIT,Active,#9F56B3,2024-03-26T11:26:01.8166667,Peter Gross
1,2d447fc5-a8e6-ee11-abc0-06b344cd22ba,ABACUS LIVE,,ABACUS,[],None,Production,Active,#9F56B3,2024-03-20T11:09:41.1433333,prismatic user
2,4e447fc5-a8e6-ee11-abc0-06b344cd22ba,ABACUS UAT,,ABACUS,[],None,UAT,Active,#9F56B3,2024-03-20T11:09:42.8366667,prismatic user
3,6f447fc5-a8e6-ee11-abc0-06b344cd22ba,ACCESS CONTROL SYSTEM LIVE,,ACCESS CONTROL SYSTEM,[],None,Production,Active,#9F56B3,2024-03-20T11:09:44.4666667,prismatic user
4,8c447fc5-a8e6-ee11-abc0-06b344cd22ba,ACCESS CONTROL SYSTEM UAT,,ACCESS CONTROL SYSTEM,[],None,UAT,Active,#9F56B3,2024-03-20T11:09:46.1433333,prismatic user
...,...,...,...,...,...,...,...,...,...,...,...
231,6d436be8-fe2c-ed11-abac-0609bdd4f50c,VMA-UAT,,VMA,[{'id': 'a141b8b2-fb2c-ed11-abac-0609bdd4f50c'...,None,UAT,Active,#9F56B3,2022-09-05T09:41:36.0833333,Peter Gross
232,042f524f-ff2c-ed11-abac-0609bdd4f50c,VPP-Prod,,VPP,[{'id': '3a98c5bd-fb2c-ed11-abac-0609bdd4f50c'...,None,Production,Active,#9F56B3,2022-09-05T09:44:34.7433333,Peter Gross
233,464e055f-ff2c-ed11-abac-0609bdd4f50c,VPP-SIT,,VPP,[{'id': '2ca90ca3-fb2c-ed11-abac-0609bdd4f50c'...,None,SIT,Active,#9F56B3,2022-09-05T09:44:56.2033333,Peter Gross
234,180ad76b-ff2c-ed11-abac-0609bdd4f50c,VPP-UAT,,VPP,[{'id': 'a141b8b2-fb2c-ed11-abac-0609bdd4f50c'...,None,UAT,Active,#9F56B3,2022-09-05T09:45:18.3566667,Peter Gross
235,81acb35b-74f3-eb11-aa71-abd023f51156,WorldPay-SBX,,WorldPay,[{'id': '0935bb5a-a3ee-eb11-aa71-abd023f51156'...,None,SIT,Online,#3366ff,2021-10-11T13:49:59.7066667,Peter Gross

In [6]:
envs = envs_list.loc[:, ['id', 'name', 'linkedSystem']].rename(columns={'name': 'Environment Name', 'linkedSystem': 'System'})
envs

,id,Environment Name,System
0,8f613e4f-2ce5-ee11-abc0-06b344cd22ba,3DCS_SIT,3DCS
1,2d447fc5-a8e6-ee11-abc0-06b344cd22ba,ABACUS LIVE,ABACUS
2,4e447fc5-a8e6-ee11-abc0-06b344cd22ba,ABACUS UAT,ABACUS
3,6f447fc5-a8e6-ee11-abc0-06b344cd22ba,ACCESS CONTROL SYSTEM LIVE,ACCESS CONTROL SYSTEM
4,8c447fc5-a8e6-ee11-abc0-06b344cd22ba,ACCESS CONTROL SYSTEM UAT,ACCESS CONTROL SYSTEM
...,...,...,...
231,6d436be8-fe2c-ed11-abac-0609bdd4f50c,VMA-UAT,VMA
232,042f524f-ff2c-ed11-abac-0609bdd4f50c,VPP-Prod,VPP
233,464e055f-ff2c-ed11-abac-0609bdd4f50c,VPP-SIT,VPP
234,180ad76b-ff2c-ed11-abac-0609bdd4f50c,VPP-UAT,VPP
235,81acb35b-74f3-eb11-aa71-abd023f51156,WorldPay-SBX,WorldPay

In [24]:
p_rels = p.Get_Rel_List(token)
rel_list = pd.DataFrame(p_rels)
rels = rel_list.loc[:, ['id', 'name', 'implementationDate']].rename(columns={'name': 'Release Name','implementationDate': 'Implementation Date'})
rels

,id,Release Name,Implementation Date
0,46f784cc-81a0-ed11-abc0-06b344cd22ba,Ticketing_r3,2024-03-31T00:00:00
1,4b183eb8-b2ae-ed11-abc0-06b344cd22ba,DemoApp Release 1.0.9,2023-03-24T00:00:00
2,1ccb9d19-d0ae-ed11-abc0-06b344cd22ba,DemoApp-R1.1.0,2023-04-20T00:00:00
3,42e06c2b-c3fb-ed11-abc0-06b344cd22ba,DemoApp-R1.2.0,2023-07-21T00:00:00
4,47ee6b56-c3fb-ed11-abc0-06b344cd22ba,DemoApp-R1.1.10,2023-06-15T00:00:00
...,...,...,...
525,7fd2a352-0daf-eb11-aa70-ad37c66ed75c,Gitlab Wrapper Phase 1 updates,2021-09-23T00:00:00
526,dc684784-0daf-eb11-aa70-ad37c66ed75c,Phase 1 update for the authentication service,2021-09-23T00:00:00
527,279b10ec-1885-eb11-aa6e-c20c63ea6612,This is from testing in postman,2022-03-17T00:00:00
528,31ffeab9-9948-ec11-ab45-0a361ec86b8c,2nd example release,2022-03-17T00:00:00
529,e006faf3-d390-ec11-ab48-0a361ec86b8c,Release Environment June Release,2022-06-23T00:00:00

In [26]:
merged_df = pd.merge(result_set, envs, left_on='environmentId', right_on='id', suffixes=('_booking', '_env'))
merged_df = merged_df[['Environment Name', 'startDate', 'endDate', 'System', 'releaseId', 'status', 'state']]
merged_df = merged_df.merge(rels, left_on='releaseId', right_on='id').rename(columns={'status': 'Booking Status','state': 'Conflict State', 'startDate': 'Start Date', 'endDate': 'End Date'})
merged_df = merged_df[['Environment Name', 'Start Date', 'End Date', 'System', 'Booking Status', 'Conflict State', 'Release Name', 'Implementation Date']]
# automatically find all columns that look like dates
date_cols = [
    col for col in merged_df.columns
    if merged_df[col].astype(str).str.match(r'\d{4}-\d{2}-\d{2}T').any()
]

# convert and reformat each detected date column
for col in date_cols:
    merged_df[col] = pd.to_datetime(merged_df[col], errors='coerce').dt.strftime('%d %b %Y %H:%M')

merged_df

,Environment Name,Start Date,End Date,System,Booking Status,Conflict State,Release Name,Implementation Date
0,Mobility_SIT,27 May 2025 00:00,29 Jul 2025 00:00,Mobility App,Pending,Conflicting,Risk Calculation App Project,20 Oct 2025 00:00
1,Mobility_SIT,03 Apr 2025 00:00,05 Jun 2025 00:00,Mobility App,Pending,Available,Mobile App IT Ops Project,27 Aug 2025 00:00

In [18]:
result_set = pd.DataFrame(p_json.get('resultSet', []))
result_set

,id,environmentId,isEnvironmentGroup,releaseId,phaseId,tebrId,startDate,endDate,status,state,statusUpdaterId,timeStamp
0,9321451d-132f-f011-abc0-06b344cd22ba,dff20bbc-082f-f011-abc0-06b344cd22ba,False,7321451d-132f-f011-abc0-06b344cd22ba,9021451d-132f-f011-abc0-06b344cd22ba,None,2025-05-27T00:00:00,2025-07-29T00:00:00,Pending,Conflicting,None,None
1,ee07dbe0-112f-f011-abc0-06b344cd22ba,dff20bbc-082f-f011-abc0-06b344cd22ba,False,cc07dbe0-112f-f011-abc0-06b344cd22ba,ea07dbe0-112f-f011-abc0-06b344cd22ba,None,2025-04-03T00:00:00,2025-06-05T00:00:00,Pending,Available,None,None

In [9]:
token = p.getAccessToken()
phases = p.Phase_id_to_name_Cache(token)
print(phases)

{'0a3e1db2-6c01-eb11-aa62-e6b22d29743d': 'PLAN', '0b3e1db2-6c01-eb11-aa62-e6b22d29743d': 'DEV', '0c3e1db2-6c01-eb11-aa62-e6b22d29743d': 'SPRINT 1', '0d3e1db2-6c01-eb11-aa62-e6b22d29743d': 'SPRINT 2', '0e3e1db2-6c01-eb11-aa62-e6b22d29743d': 'SPRINT 3', '0f3e1db2-6c01-eb11-aa62-e6b22d29743d': 'SIT', '103e1db2-6c01-eb11-aa62-e6b22d29743d': 'UAT', 'ff2be071-7482-eb11-aa6e-c20c63ea6612': 'PAT', '113e1db2-6c01-eb11-aa62-e6b22d29743d': 'STAGE', '123e1db2-6c01-eb11-aa62-e6b22d29743d': 'PROD', '5e9eff2d-a3f6-eb11-aa71-abd023f51156': 'Sandbox', '5f9eff2d-a3f6-eb11-aa71-abd023f51156': 'ST', '609eff2d-a3f6-eb11-aa71-abd023f51156': 'PREPRD', '619eff2d-a3f6-eb11-aa71-abd023f51156': 'BRKFIX', '629eff2d-a3f6-eb11-aa71-abd023f51156': 'Training', '624e6592-cb57-ee11-abc0-06b344cd22ba': 'Heatmap Plan'}

In [3]:
from neo4j import GraphDatabase
URI = "bolt://192.168.1.65:7687"
AUTH = ("neo4j","password")
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()

In [1]:
import plutora as p
bookings = p.Get_Bookings()
bookings

,Environment Name,Start Date,End Date,System,Booking Status,Conflict State,Release Name,Implementation Date
0,Mobility_SIT,27 May 2025 00:00,29 Jul 2025 00:00,Mobility App,Pending,Conflicting,Risk Calculation App Project,20 Oct 2025 00:00
1,Mobility_SIT,03 Apr 2025 00:00,05 Jun 2025 00:00,Mobility App,Pending,Available,Mobile App IT Ops Project,27 Aug 2025 00:00

In [3]:
import plutora as p
tecrs = p.Get_TECRs("2024-01-01", "2024-12-31")
tecrs

,id,TECR No,Title,TECR Type,Assigned To,Start Date,Due Date,Description,Release Name,TECR Status,...,Outage Start Date,Outage End Date,Build Name,CRQ,Outage Category,Outage Type,Project,Request Type,Test,Version
0,34ebed6d-eeab-ee11-abc0-06b344cd22ba,ER167,ReactDemo R1.0.0 2024-01-05,Application,prismatic user,05 Jan 2024 17:11,05 Jan 2024 17:11,Changes included: <br><br><br><a href='https:/...,ReactDemo_R1.0.0,Completed,...,,,,,,,,,,
1,94d54249-c2ac-ee11-abc0-06b344cd22ba,ER168,ReactDemo R1.0.0 2024-01-05,Application,prismatic user,05 Jan 2024 17:11,05 Jan 2024 17:11,Changes included: <br><br><br><a href='https:/...,ReactDemo_R1.0.0,Completed,...,,,,,,,,,,
2,a54d72f3-19ae-ee11-abc0-06b344cd22ba,ER169,ReactDemo R1.0.0 2024-01-08,Application,prismatic user,08 Jan 2024 11:34,08 Jan 2024 11:34,Changes included: <br><br><br><a href='https:/...,ReactDemo_R1.0.0,Completed,...,,,,,,,,,,
3,4199fabe-cfae-ee11-abc0-06b344cd22ba,ER170,ReactDemo R1.0.0 2024-01-09,Application,prismatic user,09 Jan 2024 09:15,09 Jan 2024 09:15,"Changes included: <br><br><br><a href=""https:/...",ReactDemo_R1.0.0,Completed,...,,,,,,N/A,,,,
4,de198c13-d1ae-ee11-abc0-06b344cd22ba,ER171,ReactDemo R1.0.0 2024-01-09,Application,prismatic user,09 Jan 2024 09:25,09 Jan 2024 09:25,"Changes included: <br><br><br><a href=""https:/...",ReactDemo_R1.0.0,Completed,...,,,,,,N/A,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083,a0478bf3-8bf3-ef11-abc0-06b344cd22ba,ER1686,Mortgage_Android Mortgage_SIT 2024-12-30,Application,Peter Gross,30 Dec 2024 05:32,30 Dec 2024 05:47,,Mortgage_R1.1.0,Completed,...,,,,,,,,,,
1084,70747efa-8bf3-ef11-abc0-06b344cd22ba,ER1690,Mortgage_IOS Mortgage_SIT 2024-12-30,Application,Peter Gross,30 Dec 2024 05:32,30 Dec 2024 05:47,,Mortgage_R1.1.0,Completed,...,,,,,,,,,,
1085,1f11f406-8cf3-ef11-abc0-06b344cd22ba,ER1694,Mortgage_Server Mortgage_SIT 2024-12-30,Application,Peter Gross,30 Dec 2024 05:32,30 Dec 2024 05:47,,Mortgage_R1.1.0,Completed,...,,,,,,,,,,
1086,eef8880d-8cf3-ef11-abc0-06b344cd22ba,ER1698,Mortgage_WEB Mortgage_SIT 2024-12-30,Application,Peter Gross,30 Dec 2024 05:32,30 Dec 2024 05:47,,Mortgage_R1.1.0,Completed,...,,,,,,,,,,
1087,acff826a-da0e-f011-abc0-06b344cd22ba,ER1847,System10_Server R1.0.5 2024-10-02,Application,prismatic user,02 Oct 2024 12:42,02 Oct 2024 12:43,Changes included: <br><br><br><a href=''>GitHu...,System10_R1.1.0,Completed,...,,,,,,,,,,

In [4]:
import pandas as pd
import plotly.express as px

# Ensure your Start Date column is in datetime format
tecrs['Start Date'] = pd.to_datetime(tecrs['Start Date'], errors='coerce')

# Extract month-year for grouping
tecrs['Month'] = tecrs['Start Date'].dt.to_period('M').astype(str)  # e.g. '2024-01'

# Count how many releases per month
monthly_counts = tecrs.groupby('Month').size().reset_index(name='Release Count')

# Create a bar chart
fig = px.bar(
    monthly_counts,
    x='Month',
    y='Release Count',
    title='Number of Releases per Month',
    labels={'Month': 'Month', 'Release Count': 'Number of Releases'},
    text='Release Count'
)

# Sort x-axis chronologically (optional)
fig.update_layout(
    xaxis={'categoryorder': 'category ascending'},
    template='plotly_white'
)

fig.show()

In [5]:
import pandas as pd
import plotly.express as px

# Ensure Start Date is datetime
tecrs['Start Date'] = pd.to_datetime(tecrs['Start Date'], errors='coerce')

# Create a month-period column for sorting
tecrs['MonthPeriod'] = tecrs['Start Date'].dt.to_period('M')

# Create a readable month label
tecrs['Month'] = tecrs['MonthPeriod'].dt.strftime('%b %Y')

# Group by MonthPeriod and TECR Status (to preserve order)
monthly_status_counts = (
    tecrs.groupby(['MonthPeriod', 'Month', 'TECR Status'])
    .size()
    .reset_index(name='Count')
    .sort_values('MonthPeriod')  # ensures chronological order
)

# Plot
fig = px.bar(
    monthly_status_counts,
    x='Month',
    y='Count',
    color='TECR Status',
    title='TECRs per month by Status',
    labels={'Month': 'Month', 'Count': 'Number of TECRs', 'TECR Status': 'Status'},
    text='Count'
)

# Format layout
fig.update_layout(
    barmode='stack',
    xaxis={'categoryorder': 'array', 'categoryarray': monthly_status_counts['Month'].unique()},
    template='plotly_white'
)

fig

In [10]:
with pd.ExcelWriter('output.xlsx', engine='xlsxwriter') as writer:
    bookings.to_excel(writer, sheet_name='Bookings', index=False)
    tecrs.to_excel(writer, sheet_name='Tecrs', index=False)

In [ ]:
import pandas as pd
import requests

# Example: you already have a dataframe
# df = pd.read_csv("input.csv")

# Function to call your API for one row
def call_api(row):
    token = p.getAccessToken()
    url = f"https://ukapi.plutora.com/TECRs/{row.id}/additionalInformation"
    headers = {
        'accept': 'application/json',
        'Plutora-Info': 'script.name=swagger',
        'Authorization': f'bearer {token}'
    }

    try:
        response = requests.get(url, headers=headers, timeout=10)
        items = response.json()
        result = {}
        for i, item in enumerate(items):
            print(f"{item}")
            name = item['name']
            data_type = item.get("dataType")

            # Pick the correct value depending on dataType
            if data_type == "FreeText":
                if item.get("text") == None:
                    result[name] = ""
                else:
                    result[name] = item.get("text")
            elif data_type == "ListField":
                if item.get("listItem") == None:
                    result[name] = ""
                else:
                    result[name] = item.get("listItem", {}).get("value")
            else:
                result[name] = ""

        return result
        # return a dict of the values you want to add


    except requests.RequestException as e:
        # handle network/API errors gracefully
        return {
            "api_status": None,
            "api_score": None,
            "api_message": f"Error: {e}"
        }

# Apply the function to each row and expand the dict into columns
results = tecrs.apply(call_api, axis=1, result_type='expand')

# Merge results back into the original dataframe
df = pd.concat([tecrs, results], axis=1)

{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': {'id': '10743748-b121-ef11-abc0-06b344cd22ba', 'value': 'Discover UK', 'sortOrder': 0, 'type': 'ChangeRequest'}, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': {'id': '82349bc0-b121-ef11-abc0-06b344cd22ba', 'value': 'Application Restart', 'sortOrder': 0, 'type': 'ChangeRequest'}, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': 'Release-121', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '77ab231a-2a1f-ef11-abc0-06b344cd22ba', 'name': 'Test', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '21426626-8877-eb11-aa67-89ba7747ce2e', 'name': 'Version', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': '', 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '29631c4e-e92f-f011-abc0-06b344cd22ba', 'name': 'Build Name', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '413ba9c8-84c0-ec11-ab81-068896e6f4fc', 'name': 'CRQ', 'type': 'ChangeRequest', 'dataType': 'FreeText', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': 'bcf3657a-9a11-ed11-ab81-068896e6f4fc', 'name': 'Outage Category', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '2b3d93af-044c-ee11-abc0-06b344cd22ba', 'name': 'Outage Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '53b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Project', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}
{'id': '54b83b30-b121-ef11-abc0-06b344cd22ba', 'name': 'Request Type', 'type': 'ChangeRequest', 'dataType': 'ListField', 'text': None, 'time': None, 'date': None, 'number': None, 'decimal': None, 'dateTime': None, 'listItem': None, 'multiListItem': None}

In [24]:
df.columns

Index(['id', 'TECR No', 'Title', 'TECR Type', 'Assigned To', 'Start Date',
       'Due Date', 'Description', 'Release Name', 'TECR Status', 'Outage',
       'Outage Start Date', 'Outage End Date', 'Build Name', 'CRQ',
       'Outage Category', 'Outage Type', 'Project', 'Request Type', 'Test',
       'Version'],
      dtype='object')

In [3]:
df = df.fillna('')
df

,id,TECR No,Title,TECR Type,Assigned To,Start Date,Due Date,Description,Release Name,TECR Status,...,Outage Start Date,Outage End Date,Build Name,CRQ,Outage Category,Outage Type,Project,Request Type,Test,Version
0,8b796a78-954a-f011-abc0-06b344cd22ba,ER1864,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,Discover UK,Application Restart,,
1,47c1f737-9c4a-f011-abc0-06b344cd22ba,ER1865,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
2,1e176369-9c4a-f011-abc0-06b344cd22ba,ER1866,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
3,673e6021-9d4a-f011-abc0-06b344cd22ba,ER1867,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
4,ae76b8a6-9d4a-f011-abc0-06b344cd22ba,ER1868,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
5,412c3fc3-a04a-f011-abc0-06b344cd22ba,ER1869,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
6,81cdb479-b44a-f011-abc0-06b344cd22ba,ER1875,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
7,d1feac36-be4a-f011-abc0-06b344cd22ba,ER1876,FSM: Deployment of release Release-121 on stag...,Software Deployment - Test,CRM Development Team,11 Jun 2025 10:56,11 Jun 2025 11:11,Import Solution: SXS.FSM.Entities<br>Import So...,,Completed,...,,,Release-121,,,,,,,
8,519203b3-ec6e-f011-abc0-06b344cd22ba,ER1878,reconfigure the customer server in SIT,Infrastructure,test peter,11 Aug 2025 06:00,11 Aug 2025 06:30,,Customer_R1.1.16,Draft,...,,,,,,,,,,
9,cf3bc2e1-f37c-f011-abc0-06b344cd22ba,ER1881,BI Build #5179 to PREPROD,Software Deployment - Test,Peter Gross,13 Aug 2025 10:24,13 Aug 2025 10:32,,,Completed,...,,,,,,,,,,
10,31ad02a7-b38c-f011-abc0-06b344cd22ba,ER1887,Customer SIT Deployment June25,Planned Deployment,Peter Gross,26 Jun 2025 23:00,27 Jun 2025 22:59,,,Draft,...,,,,,,,,,,
11,52e488ab-b68c-f011-abc0-06b344cd22ba,ER1888,Customer SIT Deployment July25,Planned Deployment,Peter Gross,24 Jul 2025 23:00,25 Jul 2025 22:59,,,Draft,...,,,,,,,,,,
12,125b82ba-b68c-f011-abc0-06b344cd22ba,ER1889,Customer SIT Deployment Aug25,Planned Deployment,Peter Gross,28 Aug 2025 23:00,29 Aug 2025 22:59,,,Draft,...,,,,,,,,,,
13,f4a0c8d2-b68c-f011-abc0-06b344cd22ba,ER1890,Customer SIT Deployment Sep25,Planned Deployment,Peter Gross,25 Sep 2025 23:00,26 Sep 2025 22:59,,,Draft,...,,,,,,,,,,
14,face02e6-b68c-f011-abc0-06b344cd22ba,ER1891,Customer SIT Deployment Oct25,Planned Deployment,Peter Gross,31 Oct 2025 00:00,31 Oct 2025 23:59,,,Draft,...,,,,,,,,,,
15,1e5f9af9-b68c-f011-abc0-06b344cd22ba,ER1892,Customer SIT Deployment Nov25,Planned Deployment,Peter Gross,28 Nov 2025 00:00,28 Nov 2025 23:59,,,Draft,...,,,,,,,,,,
16,31861982-b78c-f011-abc0-06b344cd22ba,ER1898,Mortgage SIT Deployment June25,Planned Deployment,Peter Gross,12 Jun 2025 23:00,13 Jun 2025 22:59,,,Draft,...,,,,,,,,,,
17,9e29cd95-b78c-f011-abc0-06b344cd22ba,ER1899,Mortgage SIT Deployment July25,Planned Deployment,Peter Gross,10 Jul 2025 23:00,11 Jul 2025 22:59,,,Draft,...,,,,,,,,,,
18,8c6460ab-b78c-f011-abc0-06b344cd22ba,ER1900,Mortgage SIT Deployment Aug25,Planned Deployment,Peter Gross,07 Aug 2025 23:00,08 Aug 2025 22:59,,,Draft,...,,,,,,,,,,
19,1a0d54c1-b78c-f011-abc0-06b344cd22ba,ER1901,Mortgage SIT Deployment Sep25,Planned Deployment,Peter Gross,11 Sep 2025 23:00,12 Sep 2025 22:59,,,Draft,...,,,,,,,,,,
20,b16ed8d5-b78c-f011-abc0-06b344cd22ba,ER1902,Mortgage SIT Deployment Oct25,Planned Deployment,Peter Gross,09 Oct 2025 23:00,10 Oct 2025 22:59,,,Draft,...,,,,,,,,,,
21,5d115aea-b78c-f011-abc0-06b344cd22ba,ER1903,Mortgage SIT Deployment Nov25,Planned Deployment,Peter Gross,14 Nov 2025 00:00,14 Nov 2025 23:59,,,Draft,...,,,,,,,,,,
22,65665416-1b8f-f011-abc0-06b344cd22ba,ER1904,Mortgage_Server 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,In Progress,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
23,171a586a-1b8f-f011-abc0-06b344cd22ba,ER1905,Mortgage_Server 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,In Progress,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
24,6c56d4f3-1b8f-f011-abc0-06b344cd22ba,ER1906,Mortgage_Server 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,In Progress,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
25,a5a51038-1c8f-f011-abc0-06b344cd22ba,ER1907,Mortgage_Server 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,In Progress,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
26,7152ab73-1c8f-f011-abc0-06b344cd22ba,ER1908,Mortgage_Server 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,In Progress,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
27,4806a19a-1c8f-f011-abc0-06b344cd22ba,ER1909,Mortgage_Server 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
28,e62260f7-1d8f-f011-abc0-06b344cd22ba,ER1910,Mortgage_Server R1.1.4 2025-09-04,Software Deployment - Test,Peter Gross,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
29,f70e368a-4a99-f011-abc0-06b344cd22ba,ER1911,BI Build #5179 to PREPROD,Software Deployment - Test,BI Development Team,13 Aug 2025 10:24,13 Aug 2025 10:32,,,Completed,...,,,,,,,,,,
30,d38ccdf4-c19e-f011-abc0-06b344cd22ba,ER1919,DB_PROVISION@2025-06-13T02:08:19,Data Refresh,Int user,13 Jun 2025 09:08,13 Jun 2025 09:08,INITIAL,,Completed,...,13 Jun 2025 09:08,13 Jun 2025 09:08,,,,,,,,
31,758dcdf4-c19e-f011-abc0-06b344cd22ba,ER1920,DB_ROLLBACK@2025-10-01T01:18:09,Data Refresh,Int user,01 Oct 2025 08:18,01 Oct 2025 08:20,ROLLBACK,,Completed,...,01 Oct 2025 08:18,01 Oct 2025 08:18,,,,,,,,
32,f8384601-c49e-f011-abc0-06b344cd22ba,ER1921,DB_PROVISION@2025-06-13T01:34:44,Data Refresh,Int user,13 Jun 2025 08:34,13 Jun 2025 08:35,INITIAL,,Completed,...,13 Jun 2025 08:34,13 Jun 2025 08:35,,,,,,,,
33,6a304407-c49e-f011-abc0-06b344cd22ba,ER1922,DB_PROVISION@2025-06-13T01:34:46,Data Refresh,Int user,13 Jun 2025 08:34,13 Jun 2025 08:36,INITIAL,,Completed,...,13 Jun 2025 08:34,13 Jun 2025 08:35,,,,,,,,
34,6edb15f5-2fa0-f011-abc0-06b344cd22ba,ER1925,DB_ROLLBACK@2025-10-01T07:59:38,Data Refresh,Int user,02 Oct 2025 14:59,02 Oct 2025 20:20,Event Type: ROLLBACK<br>Data Timestamp: 2025-0...,,Completed,...,02 Oct 2025 14:59,02 Oct 2025 20:19,,,,,,,,
35,77cb09fc-2fa0-f011-abc0-06b344cd22ba,ER1926,DB_ROLLBACK@2025-10-02T13:45:25,Data Refresh,Int user,02 Oct 2025 20:45,02 Oct 2025 20:48,Event Type: ROLLBACK<br>Data Timestamp: 2025-0...,,Completed,...,02 Oct 2025 20:45,02 Oct 2025 20:45,,,,,,,,
36,b22bafb6-90a2-f011-abc0-06b344cd22ba,ER1927,DB_ROLLBACK@2025-10-06T01:43:15,Data Refresh,Int user,06 Oct 2025 08:43,06 Oct 2025 08:44,Event Type: ROLLBACK<br>Data Timestamp: 2025-0...,,Completed,...,06 Oct 2025 08:43,06 Oct 2025 08:43,,,,,,,,
37,f32bafb6-90a2-f011-abc0-06b344cd22ba,ER1928,DB_ROLLBACK@2025-10-06T01:42:55,Data Refresh,Int user,06 Oct 2025 08:42,06 Oct 2025 08:43,Event Type: ROLLBACK<br>Data Timestamp: 2025-0...,,Completed,...,06 Oct 2025 08:42,06 Oct 2025 08:43,,,,,,,,
38,b24a9454-d6a8-f011-abc0-06b344cd22ba,ER1929,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,Int user,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
39,49c1e972-d6a8-f011-abc0-06b344cd22ba,ER1930,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,Int user,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
40,ed612feb-d8a8-f011-abc0-06b344cd22ba,ER1931,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,Int user,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
41,a3d09776-d9a8-f011-abc0-06b344cd22ba,ER1932,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,Int user,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
42,70a3f4bb-e0a8-f011-abc0-06b344cd22ba,ER1933,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,Int user,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
43,564a9008-e1a8-f011-abc0-06b344cd22ba,ER1934,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,Int user,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,
44,963ad98c-e2a8-f011-abc0-06b344cd22ba,ER1935,Mortgage_Server R1.1.4 2025-09-04,Planned Deployment,JDE 9.2 Development Team,04 Sep 2025 15:26,04 Sep 2025 16:26,A Description,Mortgage_R1.1.4,Completed,...,04 Sep 2025 15:26,04 Sep 2025 15:56,,,,,,,,

In [1]:
import plutora as p
releases = p.Get_Releases("2024-01-01", "2024-12-31")
releases

,id_release,identifier,name,Release State,implementationDate,plutoraReleaseType,releaseStatusMode,AgilePlaceRelId,AgilePlaceSysId,Categories,JiraId,Programme,Project
0,46f784cc-81a0-ed11-abc0-06b344cd22ba,Ticketing_r3,Ticketing_r3,Approved,2024-03-31T00:00:00,Independent,Execution,,,,,FAP P1,Ticketing FAP
1,7054e630-8858-ee11-abc0-06b344cd22ba,PR-1200,Demo App - Phase 3,Draft,2024-03-31T00:00:00,Independent,Planning,,,,,,
2,f6857794-8858-ee11-abc0-06b344cd22ba,PR-1201,Demo App - Phase 4,Draft,2024-06-30T00:00:00,Independent,Planning,,,,,,
3,0945f9ad-8858-ee11-abc0-06b344cd22ba,PR-1202,Demo App - Phase 5,Completed,2024-09-30T00:00:00,Independent,Completed,,,,,,
4,3da353cc-8858-ee11-abc0-06b344cd22ba,PR-1203,Demo App - Phase 6,Draft,2024-12-29T00:00:00,Independent,Planning,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,fcff1902-67f0-ef11-abc0-06b344cd22ba,Insurance_R1.0.21,Insurance_R1.0.21,Completed,2024-11-01T00:00:00,Independent,Completed,,,,,,
166,d6011a02-67f0-ef11-abc0-06b344cd22ba,Insurance_R1.0.22,Insurance_R1.0.22,Completed,2024-11-15T00:00:00,Independent,Completed,,,,,,
167,b2031a02-67f0-ef11-abc0-06b344cd22ba,Insurance_R1.0.23,Insurance_R1.0.23,Completed,2024-11-29T00:00:00,Independent,Completed,,,,,,
168,65fb5608-67f0-ef11-abc0-06b344cd22ba,Insurance_R1.0.24,Insurance_R1.0.24,Completed,2024-12-13T00:00:00,Independent,Completed,,,,,,
169,105f035e-1b18-ef11-abc0-06b344cd22ba,Sales Release July,Sales Release July,Draft,2024-07-31T00:00:00,Enterprise,Planning,,,,,Sales Updates 2024,

In [2]:
releases.columns

Index(['id_release', 'identifier', 'name', 'releaseStatusTypeId',
       'releaseStatusType', 'implementationDate', 'displayColor',
       'plutoraReleaseType', 'releaseProjectType', 'lastModifiedDate',
       'releaseStatusMode', 'parentReleaseId', 'parentRelease',
       'AgilePlaceRelId', 'AgilePlaceSysId', 'Automated Tests%',
       'Business Objective', 'Categories', 'Environment Notes',
       'Environment Statements', 'Gitlab Milestone', 'Gitlab Project',
       'IT Testing Type', 'JiraId', 'Milestone',
       'Overridden Release by Management', 'P1', 'P2', 'P3', 'Programme',
       'Project', 'RAG', 'Wupos Release Type', 'id_state', 'Release State'],
      dtype='object')